### ISSUE TITLE
Failure while creating glidein tar ball

### ISSUE THREAD

**Issue by AshishPandey90** [WIPACrepo/pyglidein#164]
I am trying to connect two machines with HTCondor installed using pyGlidin service to run  job.

It's mostly has been trial and error approach for me to set it up. I will highly appreciate it if I can get more documents related to pyGlidein for setup.  I am facing below issue while creating glidein tar ball. It will  be a great help if someone knows about this issue or have faced this earlier and have been able to resolve it.

Command used :
 python ./create_glidein_tarball.py --output demo --template-dir glidein_template --htcondor-version condor-8.8.1

I do not find enough documentation to understand content of --template-dir, so I used the template given with the github. But Its failing with below issue

Error:
make[2]: *** [cvmfs/CMakeFiles/cvmfs_only.dir/authz/authz_curl.cc.o] Error 1
make[1]: *** [cvmfs/CMakeFiles/cvmfs_only.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "./create_glidein_tarball.py", line 234, in <module>
    main()
  File "./create_glidein_tarball.py", line 213, in main
    parrot_path = parrot_build(**parrot_opts)
  File "./create_glidein_tarball.py", line 96, in parrot_build
    cvmfs = cvmfs_build()
  File "./create_glidein_tarball.py", line 81, in cvmfs_build
    subprocess.check_call(['make'])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2

Scanning dependencies of target cvmfs_only
[ 16%] Building CXX object cvmfs/CMakeFiles/cvmfs_only.dir/authz/authz.cc.o
[ 18%] Building CXX object cvmfs/CMakeFiles/cvmfs_only.dir/authz/authz_curl.cc.o
cvmfs/CMakeFiles/cvmfs_only.dir/build.make:86: recipe for target 'cvmfs/CMakeFiles/cvmfs_only.dir/authz/authz_curl.cc.o' failed
CMakeFiles/Makefile2:535: recipe for target 'cvmfs/CMakeFiles/cvmfs_only.dir/all' failed
Makefile:151: recipe for target 'all' failed

**Comment by dsschult** [comment]
My best guess is that you're missing a dependency for curl.  I remember needing to install a lot of dev packages to get the tarball creation working.

Is there more of the error log that can pinpoint what went wrong?

**Comment by AshishPandey90** [comment]
Hi Davis,
 Thank you for your response. I am trying to debug through the logs to check for dependency. Please find attached the logs generated with the command.

command:
python ./create_glidein_tarball.py --output demo --template-dir glidein_template --htcondor-version condor-8.8.1 >> tar_logs_4.txt

[tar_logs_4.txt](https://github.com/WIPACrepo/pyglidein/files/3412575/tar_logs_4.txt)
[Console_Logs.txt](https://github.com/WIPACrepo/pyglidein/files/3412576/Console_Logs.txt)

**Comment by dsschult** [comment]
So this looks like a gcc version issue.  It works fine on centos 7, which was our target platform.

The solution is probably to use updated versions of the packages in the create_glidein_tarball.py script.  They are 2+ years out of date now.  If you want to experiment with this, go ahead.  I don't currently have time now to do this.
