### ISSUE TITLE
The tool resources/solicit-token.sh doesn't work at NERSC

### ISSUE THREAD

**Issue by jnbellinger** [WIPACrepo/pyglidein#187]
You are using Python 3.6. This version does not support timestamps with nanosecond precision and the OpenTelemetry SDK will use millisecond precision instead. Please refer to PEP 564 for more information. Please upgrade to Python 3.7 or newer to use nanosecond precision.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/u2/i/icecubed/NEWLTA/lta/resources/solicit_token.py", line 25, in <module>
    asyncio.run(solicit_token(config["TOKEN_SERVICE_URL"], config["LTA_AUTH_ROLE"]))
AttributeError: module 'asyncio' has no attribute 'run'

**Comment by dsschult** [comment]
`asyncio.run()` was introduced in Python 3.7
